In [4]:
#Step 1

In [5]:
import pandas as pd
import numpy as np
import seaborn as sns

In [6]:
#Step 2

In [7]:
iris = sns.load_dataset('iris')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
#Step 3

In [9]:
iris =iris.drop(['species'], axis=1)
iris .head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [10]:
#Step 4

In [11]:
iris['sepal_sum'] = iris.sepal_length + iris.sepal_width
iris['petal_sum'] = iris.petal_length + iris.petal_width
iris.head()

   sepal_length  sepal_width  petal_length  petal_width  sepal_sum  petal_sum
0           5.1          3.5           1.4          0.2        8.6        1.6
1           4.9          3.0           1.4          0.2        7.9        1.6
2           4.7          3.2           1.3          0.2        7.9        1.5
3           4.6          3.1           1.5          0.2        7.7        1.7
4           5.0          3.6           1.4          0.2        8.6        1.6

In [23]:
#Step 5

In [27]:
mean = [np.mean(iris['sepal_length']),
        np.mean(iris['sepal_width']),
        np.mean(iris['sepal_sum']),
        np.mean(iris['petal_length']),
        np.mean(iris['petal_width']),
        np.mean(iris['petal_sum'])]

std = [np.std(iris['sepal_length']),
       np.std(iris['sepal_width']),
       np.std(iris['sepal_sum']),
       np.std(iris['petal_length']),
       np.std(iris['petal_width']),
       np.std(iris['petal_sum'])]

min = [np.min(iris['sepal_length']),
       np.min(iris['sepal_width']),
       np.min(iris['sepal_sum']),
       np.min(iris['petal_length']),
       np.min(iris['petal_width']),
       np.min(iris['petal_sum'])]

max = [np.max(iris['sepal_length']),
       np.max(iris['sepal_width']),
       np.max(iris['sepal_sum']),
       np.max(iris['petal_length']),
       np.max(iris['petal_width']),
       np.max(iris['petal_sum'])]

summary_dict = {'mean' : mean, 'std' : std, 'min' : min, 'max' : max}

summary_df = pd.DataFrame(data = summary_dict, index = ['sepal_length', 'sepal_width', 'sepal_sum', 'petal_length', 'petal_width', 'petal_sum'])
summary_df

                  mean       std  min   max
sepal_length  5.843333  0.825301  4.3   7.9
sepal_width   3.057333  0.434411  2.0   4.4
sepal_sum     8.900667  0.886303  6.8  11.7
petal_length  3.758000  1.759404  1.0   6.9
petal_width   1.199333  0.759693  0.1   2.5
petal_sum     4.957333  2.499316  1.2   9.2